config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'pages#home'
  resources :dashboard
  resources :categories
  resources :products
  get '/profile', to: 'profile#index'
  get '/set_theme', to: 'theme#update'
  get '/set_sidebar', to: 'theme#sidebar'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validates :item_name, presence: true
  validates :description, presence: true
  validates :sku, presence: true
  validates :category, presence: true
  validates :quantity_on_hand, presence: true
  validates :sale_price_per_unit, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def initialize
      super
      @backend_service = BackendService.new
    end

    def index
      items = @backend_service.get_items()
      @items_by_category = items.group_by { |item| item["category"] }
    end

    def show
      all_items = @backend_service.get_items()
      items_by_category = all_items.group_by { |item| item["category"] }
      @category = params[:id]
      @items = items_by_category[@category] || []
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to dashboard_index_path
    else
      redirect_to new_user_session_path
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def initialize
    super
    @backend_service = BackendService.new
  end

  def index
    @items = @backend_service.get_items()
  end

  def new
    items = @backend_service.get_items()
    @items_by_category = items.group_by { |item| item["category"] }
  end

  def create
    @item = Item.new(product_params)
    if @item.valid?
      @resp = @backend_service.create_item(@item)
      if @resp.code == 201
        redirect_to products_path, notice: "Producto cargado exitosamente"
      else
        redirect_to :new, notice: "Error al cargar el producto"
      end
    end
  end

  def edit
    @item = @backend_service.get_item(params[:id])
    items = @backend_service.get_items()
    @items_by_category = items.group_by { |item| item["category"] }
  end

  def update
    @item = @backend_service.get_item(params[:id])
    @item.item_name = params[:item][:item_name] unless params[:item][:item_name] == ""
    @item.description = params[:item][:description] unless params[:item][:description] == ""
    @item.brand = params[:item][:brand] unless params[:item][:brand] == ""
    @item.sku = params[:item][:sku] unless params[:item][:sku] == ""
    @item.category = params[:item][:category] unless params[:item][:category] == ""
    @item.quantity_on_hand = params[:item][:quantity_on_hand] unless params[:item][:quantity_on_hand] == ""
    @item.sale_price_per_unit = params[:item][:sale_price_per_unit] unless params[:item][:sale_price_per_unit] == ""

    @resp = @backend_service.update_item(@item, params[:id])
    if @resp.code == 200
      redirect_to products_path, notice: "Producto editado exitosamente"
    else
      redirect_to :edit, notice: "Error al cargar el producto"
    end
  end

  def destroy
    p "+++++++++++++++++++++"
    p "destroy method"
    @resp = @backend_service.delete_item(params[:id])
    if @resp.code == 200
      redirect_to products_path, notice: "Producto eliminado exitosamente"
    else
      redirect_to products_path, notice: "Error al eliminar el producto"
    end
  end

  private

  def product_params
    params.require(:item).permit(:item_name, :description, :sku, :brand, :category, :quantity_on_hand, :sale_price_per_unit)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/theme_controller.rb
class ThemeController < ApplicationController
  def update
    cookies[:theme] = params[:theme]
    redirect_to(request.referrer || root_path)
  end

  def sidebar
    cookies[:sidebar] = params[:sidebar]
    redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/price_formatter_helper.rb
module PriceFormatterHelper
  def format_price(price)
    formatted_price = sprintf('%.2f', price) # Add two decimal places
    whole_part, decimal_part = formatted_price.split('.')
    whole_part.gsub!(/(\d)(?=(\d\d\d)+(?!\d))/, '\\1.') # Add dot separator every three digits in the whole part
    formatted_price = "$#{whole_part},#{decimal_part}" # Add dollar sign and comma
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def get_title_emoji(title)
    title = title.downcase
    emoji = ""
    case title
      when "alimentos"
        emoji = "🍖"
      when "autos"
        emoji = "🚗"
      when "juegos"
        emoji = "🧩"
      when "ropa"
        emoji = "👕"
      when "tech"
        emoji = "📱"
      else
        emoji = "📦"
    end
    return emoji
  end
end

app/views/categories/index.html.erb
<div class="productos">
  <%= render partial: 'shared/section_title', locals: {title: "Categorías", backButton: false} %>
  <div class="row">
    <% @items_by_category.each do |category, items| %>
      <div class="col-12 col-md-6">
        <%= render partial: 'shared/custom_collapsible', locals: {title: category.upcase, items: items} %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="detalle-categoria">
  <%= render partial: 'shared/section_title', locals: {title: @category.capitalize, backButton: true} %>
  <div class="table-responsive">
    <table class="table table-hover table-sm align-middle">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Descripcion</th>
          <th scope="col">SKU</th>
          <th scope="col">Stock</th>
          <th scope="col">Precio</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.item_name %></td>
            <td><%= item.description %></td>
            <td><%= item.sku %></td>
            <td><%= item.quantity_on_hand %></td>
            <td><%= format_price(item.sale_price_per_unit) %></td>
            <td>
              <%= link_to edit_product_path(item._uuid) do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
            </td>
            <td>
              <a type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">
                <i class="bi bi-trash"></i>
              </a>
              <%= render partial: 'shared/delete_confirmation', locals: {id: item._uuid} %>
            </td>
          </tr>
        <% end %>
        <% total_quantity_on_hand = @items.sum(&:quantity_on_hand) %>
        <% total_sale_price_per_unit = @items.sum(&:sale_price_per_unit) %>
        <tr class="table-totals">
          <td></td>
          <td></td>
          <td></td>
          <td><strong><%= total_quantity_on_hand %></strong></td>
          <td><strong><%= format_price(total_sale_price_per_unit) %></strong></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryApp</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />
    <link rel="icon" type="image/x-icon" href="<%= asset_path('favicon.ico') %>" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;700&display=swap" rel="stylesheet">
    <script>
      if (localStorage.getItem('darkMode') === 'true') {
        document.documentElement.classList.add('dark');
      }
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

  <body class="<%= cookies[:theme] %>">
    <div class="spinner placeholder-glow" role="status">
      <%= image_tag("favicon.ico", width: "50") %>
    </div>
    <% if user_signed_in? %>
      <%= render 'shared/header' %>
    <% end %>
    <div class="container-fluid root-div <%= user_signed_in? ? "logged-in" : "not-logged-in" %>">
      <div class="row me-3">
        <% if user_signed_in? %>
          <%= render 'shared/side_menu' %>
        <% end %>
        <main class="mx-auto px-md-4 <%= user_signed_in? ? "col" : "col-12 col-md-4 mx-auto" %>">
        <%= yield %>
        </main>
      </div>
    </div>
    <%= render partial: 'shared/logout' %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with url: url, model: @item, method: method, class: "product-form", local: true do |form| %>
  <div class="form-group mb-3">
    <%= form.label :item_name, "Nombre" %>
    <%= form.text_field :item_name, class: "form-control", name: "item[item_name]" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :description, "Descripción" %>
    <%= form.text_area :description, class: "form-control", name: "item[description]" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :brand, "Marca" %>
    <%= form.text_field :brand, class: "form-control", name: "item[brand]" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :sku, "SKU" %>
    <%= form.text_field :sku, class: "form-control", name: "item[sku]" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :category, "Categoría" %>
    <%= form.select :category, options_for_select(@items_by_category.keys.map { |category| [category.capitalize, category] }), {}, { class: "form-control", name: "item[category]" } %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :quantity_on_hand, "Stock" %>
    <%= form.number_field :quantity_on_hand, class: "form-control", name: "item[quantity_on_hand]" %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :sale_price_per_unit, "Precio" %>
    <%= form.number_field :sale_price_per_unit, class: "form-control", name: "item[sale_price_per_unit]" %>
  </div>
  <%= form.submit "Guardar", class: "btn btn-primary" %>
<% end %>

app/views/products/edit.html.erb
<%= render partial: 'shared/section_title', locals: {title: "Editar producto", backButton: true} %>
<%= render partial: 'form', locals: {url: product_path, method: "PATCH"} %>

app/views/products/index.html.erb
<div class="inventario">
  <%= render partial: 'shared/section_title', locals: {title: "Productos", backButton: false} %>
  <div class="table-responsive">
    <table class="table table-hover table-sm align-middle">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Descripcion</th>
          <th scope="col">SKU</th>
          <th scope="col">Categoria</th>
          <th scope="col">Stock</th>
          <th scope="col">Precio</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.item_name %></td>
            <td><%= item.description %></td>
            <td><%= item.sku %></td>
            <td><%= item.category %></td>
            <td><%= item.quantity_on_hand %></td>
            <td><%= format_price(item.sale_price_per_unit) %></td>
            <td>
              <%= link_to edit_product_path(item._uuid) do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
            </td>
            <td>
              <a type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">
                <i class="bi bi-trash"></i>
              </a>
              <%= render partial: 'shared/delete_confirmation', locals: {id: item._uuid} %>
            </td>
          </tr>
        <% end %>
        <% total_quantity_on_hand = @items.sum(&:quantity_on_hand) %>
        <% total_sale_price_per_unit = @items.sum(&:sale_price_per_unit) %>
        <tr class="table-totals">
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><strong><%= total_quantity_on_hand %></strong></td>
          <td><strong><%= format_price(total_sale_price_per_unit) %></strong></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/products/new.html.erb
<%= render partial: 'shared/section_title', locals: {title: "Nuevo producto", backButton: true} %>
<%= render partial: 'form', locals: {url: products_path, method: "POST"} %>

app/views/shared/_custom_collapsible.html.erb
<div class="card mb-4 border-0 border-bottom rounded-0 bg-transparent">
  <div class="card-body">
    <a data-bs-toggle="collapse" href="#<%= title %>" role="button" aria-expanded="false" aria-controls=<%= title %> class="collapse-button text-reset text-decoration-none">
      <div class="row align-items-center">
        <div class="col d-flex flex-row align-items-center">
          <div class="p-2"><%= get_title_emoji(title) %></div>
          <h5 class="card-title mb-0"><%= title %></h5>
        </div>
        <div class="col-auto text-end">
          <i class="bi bi-chevron-down"></i>
        </div>
      </div>
    </a>
    <div class="collapse" id=<%= title %>>
      <div class="card card-body border-0 px-0 bg-transparent">
        <ul class="mb-0">
          <% items.first(5).each do |item| %>
            <li>
              <%= item.item_name %>
            </li>
          <% end %>
        </ul>
        <% if items.size > 5 %>
          <div class="mt-2 text-end">
            <%= link_to "Ver más", category_path(title.downcase), class: "link-offset-2" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_delete_confirmation.html.erb
<div class="modal fade" id="deleteConfirmationModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content text-center p-2">
      <div class="modal-header justify-content-center border-0 p-2">
        <h1 class="modal-title fs-6" id="deleteConfirmationModalLabel">¿Estás seguro que querés eliminar este producto?</h1>
      </div>
      <div class="modal-body p-2 mx-4 fw-light">
        Una vez confirmada, esta acción <strong> no podrá revertirse</strong>.
      </div>
      <div class="modal-footer justify-content-center border-0 p-2">
        <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Cancelar</button>
        <%= link_to "Confirmar", product_path(id), data: {turbo_method: :delete}, class: "btn btn-primary btn-confirm" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to root_path, class: "text-decoration-none header-logo" do %>
      <%= image_tag("favicon.ico", width: "35", class: "pe-2") %>
      InApp
    <% end %>
    <div class="d-flex flex-row align-items-center">
      <% if (cookies[:theme] == 'dark') %>
        <%= link_to set_theme_path(theme: 'light'), class: "darkModeToggler me-4" do %>
          <i class="bi bi-moon"></i>
        <% end %>
      <% else %>
        <%= link_to set_theme_path(theme: 'dark'), class: "darkModeToggler me-4" do %>
          <i class="bi bi-moon-fill"></i>
        <% end %>
      <% end %>
      <%= render partial: 'shared/notifications_dropdown' %>
      <div class="border-start logout-dropdown" id="navbarNavDarkDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <button class="btn bg-transparent border-0 shadow-none" data-bs-toggle="dropdown" aria-expanded="false">
              <img class="object-fit-cover rounded-circle" src="https://lh3.googleusercontent.com/a/AAcHTtco_XUlCV6TN1i83dbP96Ot1qLfnqXo0_phw45kq4k=s576-c-no" alt="Avatar image" width=35 class="rounded-circle border border-light-subtle border-2">
              Belen Y.
            </button>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li>
                <%= link_to "Perfil", profile_path, class: "dropdown-item text-xs" %>
              </li>
              <li>
                <a type="button" class="dropdown-item text-xs" data-bs-toggle="modal" data-bs-target="#logoutModal">
                  Cerrar sesión
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_logout.html.erb
<div class="modal fade" id="logoutModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content text-center p-2">
      <div class="modal-header justify-content-center border-0 p-2">
        <h1 class="modal-title fs-6" id="logoutModalLabel">¿Cerrar sesión?</h1>
      </div>
      <div class="modal-body p-2 mx-4 fw-light">
        Tendrás que volver a ingresar email y contraseña para volver a usar <strong>InApp</strong>.
      </div>
      <div class="modal-footer justify-content-center border-0 p-2">
        <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Cancelar</button>
        <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_notifications_dropdown.html.erb
<div class="dropdown notifications-dropdown">
  <a class="position-relative" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="bi bi-bell pe-4"></i>
    <i class="bi bi-circle-fill pe-4 position-absolute"></i>
  </a>
  <ul class="dropdown-menu p-0 <%= cookies[:theme] == 'dark' ? 'dropdown-menu-dark' : '' %> ">
    <li class="dropdown-item border-bottom d-flex flex-column justify-content-center p-2">
      <small>8 min</small>
      <div class="row align-items-center">
        <div class="col">
          <div class="text-wrap">
            <strong>Marcos Ramírez</strong> agregó un nuevo producto al <%= link_to "inventario", products_path %>.
          </div>
        </div>
        <div class="col-auto">
          <img class="object-fit-cover rounded-circle" width=25 height=25 src="https://img.freepik.com/foto-gratis/porait-chico-lindo-cafe_23-2148436119.jpg?w=1380&t=st=1686081273~exp=1686081873~hmac=21d286fe4217eedc40e4baea1bccc72505803927fdc47cbbcf83afb9c367d655" alt="...">
        </div>
      </div>
    </li>
    <li class="dropdown-item border-bottom d-flex flex-column justify-content-center p-2">
      <small>17 min</small>
      <div class="row align-items-center">
        <div class="col">
          <div class="text-wrap">
            <strong>Alejandra Alonso</strong> eliminó <b>3</b> productos de la categoría <%= link_to "alimentos", category_path("alimentos") %>.
          </div>
        </div>
        <div class="col-auto">
          <img class="object-fit-cover rounded-circle" width=25 height=25 src="https://img.freepik.com/foto-gratis/mujer-interesada-cabello-ondulado-tomando-selfie_197531-16717.jpg?w=1380&t=st=1686081312~exp=1686081912~hmac=53db0774416ceb7144e407262984ec0b5be4800b7949e5bc04e85454ac71e0fc" alt="...">
        </div>
      </div>
    </li>
    <li class="dropdown-item border-bottom d-flex flex-column justify-content-center p-2">
      <small>31 min</small>
      <div class="row align-items-center">
        <div class="col">
          <div class="text-wrap">
            <strong>Sofía Martínez</strong> agregó el gráfico "Fuentes de ingreso" al <%= link_to "dashboard", dashboard_index_path %>.
          </div>
        </div>
        <div class="col-auto">
          <img class="object-fit-cover rounded-circle" width=25 height=25 src="https://img.freepik.com/foto-gratis/selfie-retrato-videollamada_23-2149186162.jpg?w=1380&t=st=1686081238~exp=1686081838~hmac=312d728b794eee70bf0a9f30a5e8d4f3c8eb08794126ddc462ae7aa6a6b21eee" alt="...">
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/shared/_section_title.html.erb
<div class="d-flex <%= !backButton ? "justify-content-between" : "justify-content-start" %> flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <% if backButton %>
    <%= link_to :back, class:"me-3" do %>
      <i class="bi bi-arrow-left-square fs-5 goback-icon"></i>
    <% end %>
  <% end %>
  <h1 class="h2 mb-0"><%= title %></h1>
  <% if title == "Productos" %>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to new_product_path do %>
      <button type="button" class="btn btn-sm">Nuevo +</button>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_side_menu.html.erb
<nav id="sidebarMenu" class="sidebarMenu col-auto d-md-block <%= cookies[:sidebar] == 'closed' ? 'sidebarMenu--collapse' : '' %>">
  <% if (cookies[:sidebar] == 'open') %>
    <%= link_to set_sidebar_path(sidebar: 'closed'), class: "toggleSidebar rounded-circle px-2 py-1 border-0" do %>
      <i class="bi bi-chevron-double-right"></i>
    <% end %>
  <% else %>
    <%= link_to set_sidebar_path(sidebar: 'open'), class: "toggleSidebar rounded-circle px-2 py-1 border-0" do %>
      <i class="bi bi-chevron-double-left"></i>
    <% end %>
  <% end %>
  <div class="position-sticky pt-3 sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item <%= 'active' if current_page?(dashboard_index_path) %>">
        <%= link_to dashboard_index_path, class: "nav-link p-0" do %>
          <i class="bi bi-view-stacked"></i>
          <span>Dashboard</span>
        <% end %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(products_path) %>">
        <%= link_to products_path, class: "nav-link p-0" do %>
          <i class="bi bi-cart2"></i>
          <span>Productos</span>
        <% end %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(categories_path) %>">
        <%= link_to categories_path, class: "nav-link p-0" do %>
          <i class="bi bi-book"></i>
          <span>Categorías</span>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link p-0" href="#">
          <i class="bi bi-file-earmark-bar-graph"></i>
          <span>Reportes</span>
        </a>
      </li>
      <li class="nav-item">
        <button type="button" class="nav-link p-0" data-bs-toggle="modal" data-bs-target="#logoutModal">
          <i class="bi bi-box-arrow-right"></i>
          <span>Cerrar sesión</span>
        </button>
      </li>
    </ul>
  </div>
</nav>
<script>
  var sidebar = document.querySelector("#sidebarMenu");
  var toggleSidebarBtn = document.querySelector(".toggleSidebar");

  toggleSidebarBtn.onclick = () => {
    sidebar.classList.toggle("sidebarMenu--collapse");
  }
</script>